INSERT INTO COUNTRIES VALUES('BG', '+359');
INSERT INTO COUNTRIES VALUES('DE', '+49');
INSERT INTO COUNTRIES VALUES('GB', '+44');
INSERT INTO COUNTRIES VALUES('US', '+1');
INSERT INTO COUNTRIES VALUES('CA', '+1');
INSERT INTO COUNTRIES VALUES('RU', '+7');
INSERT INTO COUNTRIES VALUES('CH', '+86');

INSERT INTO COUNTRY_TRANSLATIONS VALUES('BG', 'EN', 'Bulgaria');
INSERT INTO COUNTRY_TRANSLATIONS VALUES('BG', 'BG', 'България');

INSERT INTO COUNTRY_TRANSLATIONS VALUES('DE', 'EN', 'Germany');
INSERT INTO COUNTRY_TRANSLATIONS VALUES('DE', 'BG', 'Германия');

INSERT INTO COUNTRY_TRANSLATIONS VALUES('GB', 'EN', 'United Kingdom');
INSERT INTO COUNTRY_TRANSLATIONS VALUES('GB', 'BG', 'Великобритания');

INSERT INTO COUNTRY_TRANSLATIONS VALUES('US', 'EN', 'United States of America');
INSERT INTO COUNTRY_TRANSLATIONS VALUES('US', 'BG', 'САЩ');

INSERT INTO COUNTRY_TRANSLATIONS VALUES('CA', 'EN', 'Canada');
INSERT INTO COUNTRY_TRANSLATIONS VALUES('CA', 'BG', 'Канада');

INSERT INTO COUNTRY_TRANSLATIONS VALUES('RU', 'EN', 'Russia');
INSERT INTO COUNTRY_TRANSLATIONS VALUES('RU', 'BG', 'Русия');

INSERT INTO COUNTRY_TRANSLATIONS VALUES('CH', 'EN', 'China');
INSERT INTO COUNTRY_TRANSLATIONS VALUES('CH', 'BG', 'Китай');






