INSERT INTO LANGUAGES VALUES ('EN');
INSERT INTO LANGUAGES VALUES ('BG');

INSERT INTO LANGUAGE_TRANSLATIONS VALUES ('EN', 'EN', 'English');
INSERT INTO LANGUAGE_TRANSLATIONS VALUES ('EN', 'BG', 'Английски');

INSERT INTO LANGUAGE_TRANSLATIONS VALUES ('BG', 'EN', 'Bulgarian');
INSERT INTO LANGUAGE_TRANSLATIONS VALUES ('BG', 'BG', 'Български');
