INSERT INTO USER_STATUSES VALUES('ACTIVE');
INSERT INTO USER_STATUSES VALUES('NOT_VERIFIED');
INSERT INTO USER_STATUSES VALUES('BLOCKED');

INSERT INTO USER_STATUS_TRANSLATIONS VALUES('ACTIVE', 'EN', 'Active');
INSERT INTO USER_STATUS_TRANSLATIONS VALUES('ACTIVE', 'BG', 'Активен');

INSERT INTO USER_STATUS_TRANSLATIONS VALUES('NOT_VERIFIED', 'EN', 'Not verified');
INSERT INTO USER_STATUS_TRANSLATIONS VALUES('NOT_VERIFIED', 'BG', 'Неверифициран');

INSERT INTO USER_STATUS_TRANSLATIONS VALUES('BLOCKED', 'EN', 'Blocked');
INSERT INTO USER_STATUS_TRANSLATIONS VALUES('BLOCKED', 'BG', 'Блокиран');